// Copyright (C) 2023-2026 Cyril LAMY
// SPDX-License-Identifier: GPL-3.0-or-later
unit uPasswordDialog;

{$mode objfpc}{$H+}

// Outils de mot de passe d'une entree: verification locale contre les valeurs lisibles, test
// de bind sur une connexion a part, calcul et ecriture (userPassword, Password Modify RFC 3062,
// unicodePwd sur AD). Une tentative par clic, aucun essai en serie, aucune conversion
// d'empreinte: ce n'est pas un outil de brute force et ca ne le deviendra pas.

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, StdCtrls, ExtCtrls, ComCtrls, Dialogs, Clipbrd,
  uAppContext, uConnections, uLdapEntry, uRtCheck;

resourcestring
  rsPwdTitle = 'Password tools';
  rsPwdEntry = 'Entry: %s';
  rsPwdNoEntry = 'No entry: local tools only.';
  rsPwdValues = 'Stored userPassword values';
  rsPwdValueCol = 'Value';
  rsPwdVerifyTab = 'Verify';
  rsPwdSetTab = 'Set';
  rsPwdModifyTab = 'Password Modify';
  rsPwdAdTab = 'Active Directory';
  rsPwdSecret = 'Password';
  rsPwdNewSecret = 'New password';
  rsPwdConfirm = 'Confirm';
  rsPwdOld = 'Current password';
  rsPwdVerify = 'Check stored values';
  rsPwdVerifyIntro = 'Check stored values: compares the password with the readable values above, offline. ' +
    'Nothing is sent to the network.';
  rsPwdTestIntro = 'Test bind: opens an independent connection to the same server and makes ONE bind with this ' +
    'entry''s DN. A failure can increase a lockout counter. The browsing session and the stored password are not changed.';
  rsPwdTestButton = 'Test bind on server';
  rsPwdTestAccepted = 'Accepted by the server at %s (%s).';
  rsPwdTestRefused = 'Refused: %s';
  rsPwdSetIntro = 'Computes the new value locally in the chosen format and writes it to userPassword; the server ' +
    'stores it as is, so it must support the format (see the note under the format). ' +
    '"Password Modify" lets the server apply its own policy and format instead.';
  rsPwdScheme = 'Format';
  rsPwdKeep = 'Keep the existing values (add the new one)';
  rsPwdSet = 'Set password...';
  rsPwdCompute = 'Compute only';
  rsPwdComputed = 'Computed value';
  rsPwdEmpty = 'Type the new password.';
  rsPwdNoTarget = 'No entry to write to: the value can only be computed.';
  rsPwdCopy = 'Copy (cleared after 30 s)';
  rsPwdModifyIntro = 'Uses the Password Modify operation (RFC 3062): the server applies its own policy and storage format.';
  rsPwdReset = 'Administrative reset';
  rsPwdChange = 'Change with current password';
  rsPwdRun = 'Send';
  rsPwdServerGenerated = 'Generated by server';
  rsPwdGeneratedByServer = 'The server generated the new password shown below. It is not stored.';
  rsPwdNotSupported = 'The server does not announce the Password Modify extended operation.';
  rsPwdEncryptedOnly = 'Password operations require an encrypted connection.';
  rsPwdNeedsServer = 'An LDIF file has no server to test a bind against: open the directory itself.';
  rsPwdMismatch = 'The two passwords differ.';
  rsPwdBusy = 'Too many password computations are running. Wait for them to finish.';
  rsPwdWriteInFlight = 'The previous change is still waiting for the server. Wait for its result.';
  rsPwdAdIntro = 'unicodePwd is never readable. Reset replaces it; change deletes the old value and adds the new one. ' +
    'The server enforces its policy and requires an encrypted connection.';
  rsPwdMustChange = 'User must change password at next logon (pwdLastSet = 0)';
  rsPwdNeverExpires = 'Password never expires (userAccountControl bit, other bits kept)';
  rsPwdCannotChange = '"User cannot change password" is a permission in the security descriptor, not a userAccountControl bit; it is not modified here.';
  rsPwdAdRun = 'Apply to Active Directory...';
  rsPwdDone = 'Done.';
  rsPwdValuesRereading = 'The entry changed with the last operation: reading it again. The values above are not ' +
    'shown until then.';
  rsPwdValuesUnavailable = 'The entry changed with the last operation and could not be read again: its previous ' +
    'values are no longer current. Close and reopen these tools to read it.';
  rsPwdValuesChanged = 'The stored values changed with the last operation and are not read yet: verify again ' +
    'once they are shown.';
  rsPwdVerifyOutdated = 'This result concerned values replaced meanwhile by the last operation: verify again.';
  rsPwdUacNotCurrent = 'userAccountControl changed with the last operation and was not read again: wait until ' +
    'the entry is shown again, or reopen these tools.';
  rsPwdClipboardWarning = 'Other applications can read the clipboard. The value is cleared after 30 seconds ' +
    'if it is still the one copied by Rottentree.';
  rsPwdForNewEntry = 'New entry: the password is stored with the entry when it is created.';
  rsPwdSetIntroNew = 'Computes the stored value locally in the chosen format. It is sent with the new entry ' +
    'when you click Create, never before; the server stores it as is, so it must support the format ' +
    '(see the note under the format). The password itself is never kept.';
  rsPwdUse = 'Use this password';
  rsPwdCancel = 'Cancel';

function ShowPasswordTools(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  AEntry: TLdapEntry): Boolean;
function CreatePasswordTools(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  AEntry: TLdapEntry): TForm;
function ComputePasswordValue(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  out AValue: RawByteString): Boolean;

type
  TPasswordValueOverride = function(out AValue: RawByteString): Boolean;

var
  PasswordValueOverride: TPasswordValueOverride = nil;

implementation

uses
  uTheme, uUiKit, uPwdCore, uPasswordSchemes, uUiInbox, uDirectoryWorker, uLdapErrors, uChangeSet,
  uConnectionProfile, uCancel, uRtBytes, uSearchModel, uPasswordWork,
  uAccountState, uRtCombo, uServerKind, uPasswordEntryState, uDirectoryService, uRtList, uRtMessage,
  uTaskTracker, uTaskDialog;

resourcestring
  rsPwdSessionLost = 'The connection changed while the server was being consulted: the outcome is ' +
    'unknown. Close and reopen these tools to read the entry again.';

type
  TPasswordTools = class(TTaskDialog)
  private
    FState: TPwdEntryState;
    FValues: TRtListGrid;
    FValuesNote: TLabel;
    FVerifyVersion: Integer;
    FVerdictShown: Boolean;
    FEntryWritten: Boolean;
    FPages: TPageControl;
    FVerifyPage, FSetPage, FModifyPage, FAdPage: TTabSheet;
    FVerifyEdit, FGenEdit, FGenConfirm, FGenValue, FModOld, FModNew, FModConfirm,
      FModGenerated: TEdit;
    FAdNew, FAdOld: TEdit;
    FVerifyResult, FGenResult, FModResult, FAdResult, FGenNote, FTestIntro,
      FCannotChange: TLabel;
    FModGenRow: TPanel;
    FScheme: TRtComboBox;
    FGenerated, FServerGenerated: RawByteString;
    FModReset, FAdReset, FAdMustChange, FAdNeverExpires, FKeepValues: TRtCheckBox;
    FTestTask, FVerifyTask, FGenTask: Int64;
    FSetPending: Boolean;
    FVerifyButton, FSetButton, FComputeButton: TButton;
    FForValue: Boolean;
    FResultValue: RawByteString;
    FClipTimer: TTimer;
    FClipText: string;
    procedure BuildUi(AActiveDirectory: Boolean);
    procedure FillValues;
    procedure EntryMayHaveChanged(var AReread: TLdapEntry);
    procedure VerifyClick(Sender: TObject);
    procedure ShowVerifyResult(const r: TPwdMultiResult);
    procedure TestClick(Sender: TObject);
    function StartCompute: Boolean;
    procedure SetClick(Sender: TObject);
    procedure ComputeClick(Sender: TObject);
    procedure SchemeChange(Sender: TObject);
    procedure CopyText(const AText: string);
    procedure CopyComputedClick(Sender: TObject);
    procedure CopyServerClick(Sender: TObject);
    procedure WriteValue(AReplace: Boolean);
    procedure ModifyClick(Sender: TObject);
    procedure AdClick(Sender: TObject);
    procedure ClipTimer(Sender: TObject);
    procedure LocalMessage(AMsg: TUiMessage);
    procedure TaskMessage(AMsg: TUiMessage; const ATask: TTrackedTask; AEnding: TTaskEnding);
    function PasswordEdit(AParent: TWinControl; const ACaption: string): TEdit;
    function ValueRow(AParent: TWinControl; const ACaption: string; AOnCopy: TNotifyEvent;
      out AEdit: TEdit): TPanel;
    procedure SetState(ALabel: TLabel; AState: TUiState; const AText: string);
  protected
    procedure ApplyShellColors; override;
    procedure SetStatus(const AText: string; AState: TUiState = usMuted); override;
  public
    constructor CreateFor(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
      AEntry: TLdapEntry);
    constructor CreateForValue(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection);
    destructor Destroy; override;
    property EntryWritten: Boolean read FEntryWritten;
  end;

// Valeur stockee montree a l'administrateur, jamais journalisee: un journal finit toujours
// par etre lu par quelqu'un d'autre.
function StoredValueText(const AValue: RawByteString): string;
begin
  if IsValidUtf8(AValue) and (Pos(#0, AValue) = 0) then
    Result := EscapeControlChars(AValue)
  else
    Result := HexEncode(AValue);
end;

procedure WipeEdit(AEdit: TEdit);
begin
  if AEdit = nil then Exit;
  AEdit.Text := StringOfChar(' ', Length(AEdit.Text));
  AEdit.Text := '';
end;

function ShowPasswordTools(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  AEntry: TLdapEntry): Boolean;
var
  d: TForm;
begin
  d := CreatePasswordTools(AOwner, ACtx, AConn, AEntry);
  try
    d.ShowModal;
    Result := TPasswordTools(d).EntryWritten;
  finally
    d.Free;
  end;
end;

function CreatePasswordTools(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  AEntry: TLdapEntry): TForm;
begin
  Result := TPasswordTools.CreateFor(AOwner, ACtx, AConn, AEntry);
end;

function ComputePasswordValue(AOwner: TComponent; ACtx: TAppContext; AConn: TDirectoryConnection;
  out AValue: RawByteString): Boolean;
var
  d: TPasswordTools;
begin
  AValue := '';
  if Assigned(PasswordValueOverride) then Exit(PasswordValueOverride(AValue));
  d := TPasswordTools.CreateForValue(AOwner, ACtx, AConn);
  try
    Result := (d.ShowModal = mrOk) and (d.FResultValue <> '');
    if Result then
    begin
      AValue := d.FResultValue;
      d.FResultValue := '';
    end;
  finally
    d.Free;
  end;
end;

constructor TPasswordTools.CreateForValue(AOwner: TComponent; ACtx: TAppContext;
  AConn: TDirectoryConnection);
begin
  // La memoire de l'instance est a zero avant le constructeur: le drapeau peut etre pose avant
  // CreateFor, qui le lit.
  FForValue := True;
  CreateFor(AOwner, ACtx, AConn, nil);
end;

constructor TPasswordTools.CreateFor(AOwner: TComponent; ACtx: TAppContext;
  AConn: TDirectoryConnection; AEntry: TLdapEntry);
begin
  inherited CreateDialog(AOwner, rsPwdTitle, 780, 700);
  SetIcon('key');
  if AConn <> nil then
  begin
    InitTasks(ACtx, AConn.Profile.Uuid);
    SetTarget(AConn.Profile.DisplayEndpoint + '  ' + AConn.Transport.StatusLabel,
      AConn.Profile.EnvironmentBadge);
  end
  else
    InitTasks(ACtx, '');
  FState := TPwdEntryState.Create(AEntry);
  Tasks.OnMessage := @TaskMessage;
  Tasks.OnUntracked := @LocalMessage;
  BuildUi((AConn <> nil) and
    (EffectiveServerKind(AConn.Profile, AConn.RootDse) = pkActiveDirectory));
  FillValues;
  if FForValue then
    AddButton(rsPwdCancel, mrCancel, False, True)
  else
    AddButton('Close', mrOk, False, True);
  FClipTimer := TTimer.Create(Self);
  FClipTimer.Enabled := False;
  FClipTimer.Interval := 30000;
  FClipTimer.OnTimer := @ClipTimer;
  ApplyTheme;
end;

destructor TPasswordTools.Destroy;
begin
  PasswordWork.CancelOwner(Self);
  // Fermeture avant l'echeance: la valeur copiee ne survit pas au dialogue. Le presse-papiers
  // n'est pas un coffre.
  if FClipTimer.Enabled then ClipTimer(nil);
  WipeString(FGenerated);
  WipeString(FServerGenerated);
  WipeString(FResultValue);
  FState.Free;
  inherited Destroy;
end;

function TPasswordTools.PasswordEdit(AParent: TWinControl; const ACaption: string): TEdit;
var
  row: TPanel;
begin
  row := MakeFieldRow(AParent, ACaption, 160);
  Result := TEdit.Create(row);
  Result.Parent := row;
  Result.Align := alClient;
  Result.PasswordChar := '*';
  Result.BorderSpacing.Around := 3;
end;

function TPasswordTools.ValueRow(AParent: TWinControl; const ACaption: string;
  AOnCopy: TNotifyEvent; out AEdit: TEdit): TPanel;
begin
  Result := MakeFieldRow(AParent, ACaption, 160);
  MakeButton(Result, rsPwdCopy, AOnCopy, alRight);
  AEdit := TEdit.Create(Result);
  AEdit.Parent := Result;
  AEdit.Align := alClient;
  AEdit.ReadOnly := True;
  AEdit.BorderSpacing.Around := 3;
end;

procedure TPasswordTools.BuildUi(AActiveDirectory: Boolean);
var
  p: TPanel;
  bar, row, computedRow: TPanel;
  ids: TStringArray;
  i: Integer;
  valuesLabel, setIntro: TLabel;
begin
  if FState.HasTarget then
    MakeLabel(Body, Format(rsPwdEntry, [FState.Dn]))
  else if FForValue then
    MakeLabel(Body, rsPwdForNewEntry)
  else
    MakeLabel(Body, rsPwdNoEntry);
  valuesLabel := MakeLabel(Body, rsPwdValues);
  // L'en-tete du TListView natif ignore le theme: on prend la liste de la coque.
  FValues := TRtListGrid.Create(Body);
  FValues.Parent := Body;
  StackTop(FValues);
  FValues.Align := alTop;
  FValues.Height := 110;
  FValues.FillWidth := True;
  FValues.AddColumn('#', 30);
  FValues.AddColumn(rsPwdValueCol, 240);
  FValues.AddColumn(rsPwdScheme, 170);
  FValues.AddColumn('Parameters', 110);
  FValues.AddColumn('Notes', 170);
  FValuesNote := MakeLabel(Body, '');
  FValuesNote.Visible := False;

  // Les onglets natifs ignorent les couleurs du theme: on les dessine nous-memes.
  FPages := MakePages(Body);

  p := AddPageBody(FPages, rsPwdVerifyTab);
  FVerifyPage := TTabSheet(p.Parent);
  MakeLabel(p, rsPwdVerifyIntro);
  FTestIntro := MakeLabel(p, rsPwdTestIntro);
  FVerifyEdit := PasswordEdit(p, rsPwdSecret);
  bar := MakePanel(p, alTop, 36);
  FVerifyButton := MakeButton(bar, rsPwdVerify, @VerifyClick);
  MakeButton(bar, rsPwdTestButton, @TestClick);
  FVerifyResult := MakeLabel(p, '');

  p := AddPageBody(FPages, rsPwdSetTab);
  FSetPage := TTabSheet(p.Parent);
  setIntro := MakeLabel(p, rsPwdSetIntro);
  row := MakeFieldRow(p, rsPwdScheme, 160);
  FScheme := TRtComboBox.Create(row);
  FScheme.Parent := row;
  FScheme.Align := alLeft;
  FScheme.Width := 280;
  FScheme.BorderSpacing.Left := 3;
  ids := PasswordRegistry.GeneratorIds;
  for i := 0 to High(ids) do
    FScheme.Items.Add(ids[i]);
  FScheme.ItemIndex := FScheme.Items.IndexOf(DEFAULT_GENERATOR_ID);
  if FScheme.ItemIndex < 0 then FScheme.ItemIndex := 0;
  FScheme.OnChange := @SchemeChange;
  FGenNote := MakeLabel(p, '');
  SchemeChange(nil);
  FGenEdit := PasswordEdit(p, rsPwdNewSecret);
  FGenConfirm := PasswordEdit(p, rsPwdConfirm);
  FKeepValues := MakeCheck(p, rsPwdKeep);
  bar := MakePanel(p, alTop, 36);
  FSetButton := MakeButton(bar, rsPwdSet, @SetClick);
  FComputeButton := MakeButton(bar, rsPwdCompute, @ComputeClick);
  computedRow := ValueRow(p, rsPwdComputed, @CopyComputedClick, FGenValue);
  FGenResult := MakeLabel(p, '');

  p := AddPageBody(FPages, rsPwdModifyTab);
  FModifyPage := TTabSheet(p.Parent);
  MakeLabel(p, rsPwdModifyIntro);
  FModReset := MakeCheck(p, rsPwdReset);
  FModReset.Checked := True;
  FModOld := PasswordEdit(p, rsPwdOld);
  FModNew := PasswordEdit(p, rsPwdNewSecret);
  FModConfirm := PasswordEdit(p, rsPwdConfirm);
  bar := MakePanel(p, alTop, 36);
  MakeButton(bar, rsPwdRun, @ModifyClick);
  FModResult := MakeLabel(p, '');
  FModGenRow := ValueRow(p, rsPwdServerGenerated, @CopyServerClick, FModGenerated);
  FModGenRow.Visible := False;

  p := AddPageBody(FPages, rsPwdAdTab);
  FAdPage := TTabSheet(p.Parent);
  MakeLabel(p, rsPwdAdIntro);
  FAdReset := MakeCheck(p, rsPwdReset);
  FAdReset.Checked := True;
  FAdOld := PasswordEdit(p, rsPwdOld);
  FAdNew := PasswordEdit(p, rsPwdNewSecret);
  FAdMustChange := MakeCheck(p, rsPwdMustChange);
  FAdNeverExpires := MakeCheck(p, rsPwdNeverExpires);
  FCannotChange := MakeLabel(p, rsPwdCannotChange);
  bar := MakePanel(p, alTop, 36);
  MakeButton(bar, rsPwdAdRun, @AdClick);
  FAdResult := MakeLabel(p, '');

  FSetPage.TabVisible := not AActiveDirectory;
  FModifyPage.TabVisible := not AActiveDirectory and (FProfileUuid <> '');
  FAdPage.TabVisible := AActiveDirectory;
  if FForValue then
  begin
    valuesLabel.Visible := False;
    FValues.Visible := False;
    FVerifyPage.TabVisible := False;
    FModifyPage.TabVisible := False;
    FAdPage.TabVisible := False;
    FSetPage.TabVisible := True;
    setIntro.Caption := rsPwdSetIntroNew;
    setIntro.WordWrap := True;
    FKeepValues.Visible := False;
    FComputeButton.Visible := False;
    computedRow.Visible := False;
    FSetButton.Caption := rsPwdUse;
  end;
  if not FState.HasTarget then
    SelectPage(FPages, FSetPage.PageIndex)
  else
    SelectPage(FPages, FVerifyPage.PageIndex);
end;

procedure TPasswordTools.ApplyShellColors;
begin
  inherited ApplyShellColors;
  // Le theme repeint tous les libelles couleur texte: avertissements et notes reprennent la
  // leur ensuite.
  FTestIntro.Font.Color := ShellStateColor(usWarning);
  FGenNote.Font.Color := ShellStateColor(usMuted);
  FCannotChange.Font.Color := ShellStateColor(usMuted);
  FValuesNote.Font.Color := ShellStateColor(usWarning);
end;

procedure TPasswordTools.SetState(ALabel: TLabel; AState: TUiState; const AText: string);
begin
  if ALabel = FVerifyResult then FVerdictShown := False;
  ALabel.Caption := AText;
  if AState = usMuted then
    ALabel.Font.Color := clAppFg
  else
    ALabel.Font.Color := ShellStateColor(AState);
end;

procedure TPasswordTools.FillValues;
var
  a: TLdapAttribute;
  i: Integer;
  info: TPwdInfo;
begin
  FValues.Clear;
  FValuesNote.Visible := FState.Stale;
  if FState.Stale then
  begin
    if FState.ReadFailed then
      FValuesNote.Caption := rsPwdValuesUnavailable
    else
      FValuesNote.Caption := rsPwdValuesRereading;
    Exit;
  end;
  if FState.Entry = nil then Exit;
  a := FState.Entry.Find('userPassword');
  if a = nil then Exit;
  for i := 0 to a.ValueCount - 1 do
  begin
    info := PasswordRegistry.Inspect(a.Values[i]);
    FValues.AddRow([IntToStr(i + 1), StoredValueText(a.Values[i]), info.DisplayName,
      info.Params, info.Note]);
  end;
end;

procedure TPasswordTools.VerifyClick(Sender: TObject);
var
  values: TPwdRawValues;
  i: Integer;
  pw: RawByteString;
begin
  if not FState.HasTarget then Exit;
  if FVerifyTask <> 0 then Exit;
  if not FState.CurrentValues(values) then
  begin
    SetState(FVerifyResult, usWarning, rsPwdValuesChanged);
    Exit;
  end;
  FVerifyVersion := FState.Version;
  pw := FVerifyEdit.Text;
  WipeEdit(FVerifyEdit);
  FVerifyTask := NextTaskId;
  if not PasswordWork.StartVerify(values, pw, Self, FVerifyTask) then
  begin
    FVerifyTask := 0;
    SetState(FVerifyResult, usWarning, rsPwdBusy);
  end
  else
  begin
    FVerifyButton.Enabled := False;
    SetState(FVerifyResult, usMuted, '...');
  end;
  WipeString(pw);
  for i := 0 to High(values) do WipeString(values[i]);
end;

procedure TPasswordTools.ShowVerifyResult(const r: TPwdMultiResult);
var
  details: string;
  i: Integer;
begin
  details := PwdMultiOutcomeText(r.Outcome);
  for i := 0 to High(r.Values) do
    details := details + LineEnding + Format('#%d %s: %s %s', [i + 1, r.Values[i].SchemeId,
      PwdStatusText(r.Values[i].Status), r.Values[i].Detail]);
  case r.Outcome of
    pmoMatch: SetState(FVerifyResult, usOk, details);
    pmoNoMatchAllVerified: SetState(FVerifyResult, usError, details);
  else
    SetState(FVerifyResult, usWarning, details);
  end;
  FVerdictShown := True;
end;

procedure TPasswordTools.EntryMayHaveChanged(var AReread: TLdapEntry);
var
  c: TDirectoryConnection;
begin
  if FState.HasTarget then FEntryWritten := True;
  Tasks.Cancel('read');
  if FState.WriteSettled(AReread) then
  begin
    c := Conn;
    if c <> nil then
      FState.ReadStarted(Tasks.ReadEntry('read', FState.Dn, EntryReadAttributes(c.Profile)))
    else
      FState.ReadStarted(0);
  end;
  if FVerdictShown then
    SetState(FVerifyResult, usMuted, rsPwdVerifyOutdated);
  FillValues;
end;

procedure TPasswordTools.TestClick(Sender: TObject);
var
  c: TDirectoryConnection;
  pw: RawByteString;
begin
  c := FCtx.Connections.Find(FProfileUuid);
  if (c = nil) or not FState.HasTarget then Exit;
  if c.Profile.LdifPath <> '' then
  begin
    SetState(FVerifyResult, usError, rsPwdNeedsServer);
    Exit;
  end;
  if c.Profile.Transport = tmPlain then
  begin
    SetState(FVerifyResult, usError, rsPwdEncryptedOnly);
    Exit;
  end;
  // Un test a la fois: un clic de plus ne fait pas taire le resultat du test en vol, et ne lance
  // pas une rafale de binds.
  if FTestTask <> 0 then Exit;
  pw := FVerifyEdit.Text;
  WipeEdit(FVerifyEdit);
  if pw = '' then Exit;
  FTestTask := NextTaskId;
  // Connexion independante: aucun rebind sur la connexion de navigation, qui changerait
  // d'identite sous les pieds de l'operateur.
  if not PasswordWork.Launch(TAuthTestThread.Create(c.Profile, FState.Dn, pw, Self, FTestTask)) then
  begin
    FTestTask := 0;
    SetState(FVerifyResult, usWarning, rsPwdBusy);
  end
  else
    SetState(FVerifyResult, usMuted, '...');
  WipeString(pw);
end;

procedure TPasswordTools.SchemeChange(Sender: TObject);
var
  sch: TPasswordScheme;
begin
  sch := PasswordRegistry.FindById(FScheme.Text);
  if sch <> nil then
    FGenNote.Caption := sch.GenerationNote
  else
    FGenNote.Caption := '';
end;

function TPasswordTools.StartCompute: Boolean;
var
  pw: RawByteString;
begin
  Result := False;
  if FGenTask <> 0 then Exit;
  if FGenEdit.Text = '' then
  begin
    SetState(FGenResult, usWarning, rsPwdEmpty);
    Exit;
  end;
  if FGenEdit.Text <> FGenConfirm.Text then
  begin
    SetState(FGenResult, usError, rsPwdMismatch);
    Exit;
  end;
  if PasswordRegistry.FindById(FScheme.Text) = nil then Exit;
  pw := FGenEdit.Text;
  WipeEdit(FGenEdit);
  WipeEdit(FGenConfirm);
  WipeString(FGenerated);
  WipeEdit(FGenValue);
  FGenTask := NextTaskId;
  if not PasswordWork.StartGenerate(FScheme.Text, pw, Self, FGenTask) then
  begin
    FGenTask := 0;
    SetState(FGenResult, usWarning, rsPwdBusy);
  end
  else
  begin
    FSetButton.Enabled := False;
    FComputeButton.Enabled := False;
    SetState(FGenResult, usMuted, '...');
    Result := True;
  end;
  WipeString(pw);
end;

procedure TPasswordTools.SetClick(Sender: TObject);
var
  c: TDirectoryConnection;
begin
  c := FCtx.Connections.Find(FProfileUuid);
  if FForValue then
  begin
    if (c <> nil) and not c.SecretsSafe then
    begin
      SetState(FGenResult, usError, rsPwdEncryptedOnly);
      Exit;
    end;
    FSetPending := StartCompute;
    Exit;
  end;
  if (c = nil) or not FState.HasTarget then
  begin
    SetState(FGenResult, usWarning, rsPwdNoTarget);
    Exit;
  end;
  if Tasks.Pending('genwrite') then
  begin
    SetState(FGenResult, usWarning, rsPwdWriteInFlight);
    Exit;
  end;
  if not c.SecretsSafe then
  begin
    SetState(FGenResult, usError, rsPwdEncryptedOnly);
    Exit;
  end;
  FSetPending := StartCompute;
end;

procedure TPasswordTools.ComputeClick(Sender: TObject);
begin
  if StartCompute then FSetPending := False;
end;

procedure TPasswordTools.CopyText(const AText: string);
begin
  if AText = '' then Exit;
  if RtMessageDlg(rsPwdTitle, rsPwdClipboardWarning, mtWarning, [mbOK, mbCancel], 0) <> mrOk then
    Exit;
  FClipText := AText;
  Clipboard.AsText := FClipText;
  FClipTimer.Enabled := False;
  FClipTimer.Enabled := True;
end;

procedure TPasswordTools.CopyComputedClick(Sender: TObject);
begin
  CopyText(FGenValue.Text);
end;

procedure TPasswordTools.CopyServerClick(Sender: TObject);
begin
  CopyText(FModGenerated.Text);
end;

procedure TPasswordTools.ClipTimer(Sender: TObject);
begin
  FClipTimer.Enabled := False;
  // On n'efface que notre copie, jamais ce que l'utilisateur a mis dans le presse-papiers depuis.
  if Clipboard.AsText = FClipText then
    Clipboard.AsText := '';
  FClipText := '';
end;

procedure TPasswordTools.WriteValue(AReplace: Boolean);
var
  c: TDirectoryConnection;
  change: TLdapChange;
  reason: string;
begin
  c := Conn;
  if (c = nil) or not FState.HasTarget or (FGenerated = '') then Exit;
  // Une seule ecriture en vol par action: une seconde ecraserait l'identifiant de tache, et la
  // reponse de la premiere partirait dans le neant.
  if Tasks.Pending('genwrite') then
  begin
    SetState(FGenResult, usWarning, rsPwdWriteInFlight);
    Exit;
  end;
  if not c.SecretsSafe then
  begin
    SetState(FGenResult, usError, rsPwdEncryptedOnly);
    Exit;
  end;
  change := NewChange(ckModify, FState.Dn);
  if AReplace then
    change.AddMod(moReplace, 'userPassword', [FGenerated])
  else
    change.AddMod(moAdd, 'userPassword', [FGenerated]);
  if SubmitWrite(Self, FCtx, Tasks, 'genwrite', change, '', reason) = 0 then
  begin
    if reason <> '' then SetState(FGenResult, usError, reason);
  end
  else
    SetState(FGenResult, usMuted, '...');
end;

procedure TPasswordTools.ModifyClick(Sender: TObject);
var
  c: TDirectoryConnection;
  sup: TLdapAttribute;
  err: TLdapError;
  oldPw, newPw: RawByteString;
begin
  c := Conn;
  if (c = nil) or not FState.HasTarget then Exit;
  // Controle avant d'effacer les champs: une saisie refusee n'a pas a etre une saisie perdue.
  if Tasks.Pending('mod') then
  begin
    SetState(FModResult, usWarning, rsPwdWriteInFlight);
    Exit;
  end;
  sup := nil;
  if c.RootDse <> nil then sup := c.RootDse.Find('supportedExtension');
  if (sup = nil) or (sup.IndexOfValue('1.3.6.1.4.1.4203.1.11.1') < 0) then
  begin
    SetState(FModResult, usError, rsPwdNotSupported);
    Exit;
  end;
  if not c.Transport.Encrypted then
  begin
    SetState(FModResult, usError, rsPwdEncryptedOnly);
    Exit;
  end;
  if FModNew.Text <> FModConfirm.Text then
  begin
    SetState(FModResult, usError, rsPwdMismatch);
    Exit;
  end;
  oldPw := FModOld.Text;
  newPw := FModNew.Text;
  WipeEdit(FModOld);
  WipeEdit(FModNew);
  WipeEdit(FModConfirm);
  try
    if Tasks.PasswordModify('mod', FState.Dn, oldPw, newPw, not FModReset.Checked, newPw <> '',
         err) = 0 then
      SetState(FModResult, usError, ErrorToText(err))
    else
    begin
      SetState(FModResult, usMuted, '...');
      FModGenRow.Visible := False;
      WipeEdit(FModGenerated);
    end;
  finally
    WipeString(oldPw);
    WipeString(newPw);
  end;
end;

procedure TPasswordTools.AdClick(Sender: TObject);
var
  c: TDirectoryConnection;
  change: TLdapChange;
  newPw, oldPw: RawByteString;
  uac: Int64;
  uacRaw, reason: string;
  handed: Boolean;
begin
  c := Conn;
  if (c = nil) or not FState.HasTarget then Exit;
  if Tasks.Pending('ad') then
  begin
    SetState(FAdResult, usWarning, rsPwdWriteInFlight);
    Exit;
  end;
  if not c.SecretsSafe then
  begin
    SetState(FAdResult, usError, rsPwdEncryptedOnly);
    Exit;
  end;
  // Controle avant d'effacer les champs: la valeur supprimee doit etre l'actuelle, pas celle
  // d'avant la derniere operation du dialogue.
  uacRaw := '';
  if FAdNeverExpires.Checked and not FState.CurrentUac(uacRaw) then
  begin
    if FState.Stale then
      SetState(FAdResult, usError, rsPwdUacNotCurrent)
    else
      SetState(FAdResult, usError, 'userAccountControl was not read: reload the entry first.');
    Exit;
  end;
  newPw := FAdNew.Text;
  oldPw := FAdOld.Text;
  WipeEdit(FAdNew);
  WipeEdit(FAdOld);
  handed := False;
  change := NewChange(ckModify, FState.Dn);
  try
    try
      if newPw <> '' then
      begin
        if FAdReset.Checked then
          change.AddMod(moReplace, 'unicodePwd', [EncodeUnicodePwd(newPw)])
        else
        begin
          change.AddMod(moDelete, 'unicodePwd', [EncodeUnicodePwd(oldPw)]);
          change.AddMod(moAdd, 'unicodePwd', [EncodeUnicodePwd(newPw)]);
        end;
      end;
      if FAdMustChange.Checked then
        change.AddMod(moReplace, 'pwdLastSet', ['0']);
      if FAdNeverExpires.Checked then
      begin
        if not TryStrToInt64(uacRaw, uac) then
        begin
          SetState(FAdResult, usError, 'userAccountControl was not read: reload the entry first.');
          change.Free;
          Exit;
        end;
        // Ancienne valeur supprimee telle que lue: si elle a bouge entre-temps, la requete
        // echoue au lieu d'ecraser. LOCKOUT et PASSWORD_EXPIRED ne sont jamais recopies, les
        // ecrire deverrouillerait le compte.
        change.AddMod(moDelete, 'userAccountControl', [uacRaw]);
        change.AddMod(moAdd, 'userAccountControl',
          [IntToStr((uac or UF_DONT_EXPIRE_PASSWD) and not UF_COMPUTED_BITS)]);
      end;
    finally
      WipeString(newPw);
      WipeString(oldPw);
    end;
    if Length(change.Mods) = 0 then
    begin
      change.Free;
      Exit;
    end;
    handed := True; // SubmitWrite possede change, meme s'il refuse
    if SubmitWrite(Self, FCtx, Tasks, 'ad', change, '', reason) = 0 then
    begin
      if reason <> '' then SetState(FAdResult, usError, reason);
    end
    else
      SetState(FAdResult, usMuted, '...');
  except
    on E: Exception do
    begin
      if not handed then change.Free;
      SetState(FAdResult, usError, E.Message);
    end;
  end;
end;

procedure TPasswordTools.SetStatus(const AText: string; AState: TUiState);
begin
  if FPages.ActivePage = FModifyPage then SetState(FModResult, AState, AText)
  else if FPages.ActivePage = FAdPage then SetState(FAdResult, AState, AText)
  else SetState(FGenResult, AState, AText);
end;

procedure TPasswordTools.TaskMessage(AMsg: TUiMessage; const ATask: TTrackedTask;
  AEnding: TTaskEnding);
var
  w: TWriteMsg;
  p: TPasswordMsg;
  e: TEntryMsg;
  none: TLdapEntry;
  target: TLabel;
begin
  if ATask.Tag = 'read' then
  begin
    none := nil;
    if (AEnding <> teStale) and (AMsg is TEntryMsg) then
    begin
      e := TEntryMsg(AMsg);
      FState.ReadDelivered(AMsg.TaskId, e.Entry);
    end
    else
      FState.ReadDelivered(AMsg.TaskId, none);
    FillValues;
    Exit;
  end;
  if ATask.Tag = 'mod' then target := FModResult
  else if ATask.Tag = 'ad' then target := FAdResult
  else target := FGenResult;
  // Ecriture d'une session remplacee, ou commande sans resultat type: issue inconnue, jamais
  // prise pour un succes. L'entree a pu changer, on part du principe que oui.
  if (AEnding = teStale) or (AMsg is TTaskFailedMsg) then
  begin
    none := nil;
    EntryMayHaveChanged(none);
    if AEnding = teStale then SetState(target, usWarning, rsPwdSessionLost)
    else SetState(target, usError, TTaskFailedMsg(AMsg).Text);
    Exit;
  end;
  if AMsg is TPasswordMsg then
  begin
    p := TPasswordMsg(AMsg);
    if p.Result.Ok or (p.Result.Error.Category = lecUnknownOutcome) then
    begin
      none := nil;
      EntryMayHaveChanged(none);
    end;
    if p.Result.Ok then
    begin
      SetState(FModResult, usOk, rsPwdDone);
      if p.Result.Generated <> '' then
      begin
        // Mot de passe choisi par le serveur: montre, copiable, jamais stocke.
        WipeString(FServerGenerated);
        FServerGenerated := p.Result.Generated;
        FModGenerated.Text := string(FServerGenerated);
        FModGenRow.Visible := True;
        SetState(FModResult, usOk, rsPwdGeneratedByServer);
      end;
    end
    else
      SetState(FModResult, usError, ErrorToText(p.Result.Error) + ' ' + p.Result.Error.Action);
  end
  else if AMsg is TWriteMsg then
  begin
    w := TWriteMsg(AMsg);
    if w.Result.Ok or (w.Result.Error.Category = lecUnknownOutcome) then
      EntryMayHaveChanged(w.Reread);
    if ATask.Tag = 'ad' then
    begin
      if w.Result.Ok then SetState(FAdResult, usOk, rsPwdDone)
      else SetState(FAdResult, usError, ErrorToText(w.Result.Error) + ' ' + w.Result.Error.Action);
    end
    else
    begin
      if w.Result.Ok then
        SetState(FGenResult, usOk, rsPwdDone)
      else
        SetState(FGenResult, usError, ErrorToText(w.Result.Error));
    end;
  end;
end;

procedure TPasswordTools.LocalMessage(AMsg: TUiMessage);
var
  t: TAuthTestMsg;
  pw: TPwdWorkMsg;
  info: TPwdInfo;
begin
  if (AMsg is TPwdWorkMsg) and (AMsg.TaskId = FVerifyTask) then
  begin
    pw := TPwdWorkMsg(AMsg);
    FVerifyTask := 0;
    FVerifyButton.Enabled := True;
    if pw.ErrorText <> '' then
      SetState(FVerifyResult, usError, pw.ErrorText)
    else if FVerifyVersion <> FState.Version then
      SetState(FVerifyResult, usWarning, rsPwdVerifyOutdated)
    else
      ShowVerifyResult(pw.Multi);
  end
  else if (AMsg is TPwdWorkMsg) and (AMsg.TaskId = FGenTask) then
  begin
    pw := TPwdWorkMsg(AMsg);
    FGenTask := 0;
    FSetButton.Enabled := True;
    FComputeButton.Enabled := True;
    if pw.ErrorText <> '' then
    begin
      FSetPending := False;
      SetState(FGenResult, usError, pw.ErrorText);
    end
    else
    begin
      WipeString(FGenerated);
      FGenerated := pw.Generated;
      pw.Generated := '';
      FGenValue.Text := string(FGenerated);
      info := PasswordRegistry.Inspect(FGenerated);
      SetState(FGenResult, usMuted, Trim(info.DisplayName + ' ' + info.Params));
      if FSetPending and FForValue then
      begin
        FSetPending := False;
        WipeString(FResultValue);
        FResultValue := Copy(FGenerated, 1, MaxInt);
        WipeEdit(FGenValue);
        ModalResult := mrOk;
      end
      else if FSetPending then
      begin
        FSetPending := False;
        WriteValue(not FKeepValues.Checked);
      end;
    end;
  end
  else if (AMsg is TAuthTestMsg) and (AMsg.TaskId = FTestTask) then
  begin
    t := TAuthTestMsg(AMsg);
    FTestTask := 0;
    if t.Accepted then
      SetState(FVerifyResult, usOk, Format(rsPwdTestAccepted, [TimeToStr(Now), t.Transport.StatusLabel]))
    else
      SetState(FVerifyResult, usError, Format(rsPwdTestRefused, [ErrorToText(t.Error)]));
  end;
end;

end.
